### ISSUE TITLE
Is there any demo subject data for me to play with?

### ISSUE THREAD

**Issue by dipterix** [beauchamplab/rave#14]
We are creating functions to download any published subjects with certain formats. Here's checking list

- [x] Preprocess demo subject 
  - [x] Large sample
  - [x] Small sample
- [x] Upload to AWS S3
- [x] rewrite `download_subject_data` function
- [x] Publish subject and method to download it
- [x] Document file structure and write vignette

**Comment by dipterix** [comment]
1. Two demo files created

#### sub-large
File size: 397MB
This file contains 50 frequencies and full preprocess data
URL:
https://s3-us-west-2.amazonaws.com/rave-demo-subject/sfn-demo/data-large.zip

#### sub-small
File size: 178MB
This file has some data removed, and may fail for some modules (reference for example)
URL:
https://s3-us-west-2.amazonaws.com/rave-demo-subject/sfn-demo/data-small.zip

2. Function `download_subject_data` created to download any subject data with certain format

Use `?download_subject_data` to see docs

Example:

```{r}
# Use your desktop as temporary folder
# Download zip file will not be removed in case you might need it later
download_subject_data(
  con = 'https://s3-us-west-2.amazonaws.com/rave-demo-subject/sfn-demo/data-large.zip', 
  temp_dir = '~/Desktop/',
  remove_zipfile = F)

# Launch rave app and a demo subject `sub_large` is downloaded
# init_app()
```

**Comment by dipterix** [comment]
> Post an issue on github directly from slack
<sub>[View in Slack](https://rave-brain.slack.com/archives/GTDP89EJV/p1593130522092800)</sub>

**Comment by XiaoyuZeng** [comment]
Hi all. I'm new to RAVE. I do think it's an incredible tool for iEEG data. However, I failed to download the demo data when I tried to play with data with this tool (I) from the link provided above; (ii) with the function download_subject_data; (iii) in the Slack workspace (I just can not log in that workspace). 

Any ideas to get the demo data? Thanks in advance.

**Comment by dipterix** [comment]
Hi @XiaoyuZeng ,

Please try `rave::finalize_installation()` using the latest version.

Thanks you.

**Comment by XiaoyuZeng** [comment]
> Hi @XiaoyuZeng ,
> 
> Please try `rave::finalize_installation()` using the latest version.
> 
> Thanks you.

This works! Thanks
