### ISSUE TITLE
Epoch Error in Loading Condition Explorer

### ISSUE THREAD

**Issue by EANesbitt** [beauchamplab/rave#21]
I encountered an error while trying to load Condition Explorer in RAVE with a new epoch. The following appeared in R when I checked:

Warning: Error in FUN: object 'electrodes' not found
  [No stack trace available]

What should I do?

**Comment by dipterix** [comment]
Check columns in your epoch file. You need to make sure column `Block` matches. For example, your block number might be `008`, Excel might change it to `8` because it thinks this is a number. To change it back, type in excel `'008`, and the block number will remain **as is**.

**Comment by EANesbitt** [comment]
I’ve done that, but I’m still getting the error. All condition info is complete, the blocks are zero-padded, and the file is in .csv format. I’m not sure what else to check.

On Mar 21, 2019, at 10:12 AM, Dipterix Wang <notifications@github.com<mailto:notifications@github.com>> wrote:

***CAUTION:*** This email is not from a BCM Source. Only click links or open attachments you know are safe.
________________________________

Check columns in your epoch file. You need to make sure column Block matches. For example, your block number might be 008, Excel might change it to 8 because it thinks this is a number. To change it back, type in excel '008, and the block number will remain as is.

**Comment by dipterix** [comment]
Please see the referenced issue above. This issue will be closed
