### ISSUE TITLE
Failure to load Epoch in Rave_Preprocess

### ISSUE THREAD

**Issue by EANesbitt** [beauchamplab/rave#27]
An error occurred in rave_preprocess after running the notch filter and wavelet; it stopped the loading of the Trial Epoch module and displayed the error: "INTERNAL ERROR: More bytes was read from the raw buffer than existed 2>0." What might be causing this problem?

**Comment by dipterix** [comment]
You might need to update `R.matlab`. This package might be too old or broken. To fix this problem, simply enter the following command in R

```
install.packages("R.matlab")
```
