### ISSUE TITLE
shift_amount must have equal length to the dimension at shift_by

### ISSUE THREAD

**Issue by XavierScherschligt** [beauchamplab/rave#42]
When attempting to generate the necessary files for group analysis (in Find + Export active electrodes), the RAVE GUI goes grey and the following log appears in the R terminal:

♥ Power Explorer - Exec time: 0.347 (secs)
✔ Rendering
✔ Rendering
✔ Rendering
✔ Rendering
✔ Rendering
✔ Number of workers switched to - 15
shift_amount must have equal length to the dimension at shift_by 
✖ shift_amount must have equal length to the dimension at shift_by
{
    write_out_data_function()
    showNotification(p("Done saving"), duration = 3, type = "message")
}
Warning: Error in [[: subscript out of bounds
  [No stack trace available]
✔ Clean up environment.

I am using the YAB demo patient and have tried a number of different configurations in the settings for this module.

**Comment by jmagnotti** [comment]
Thanks for submitting this bug report. We have confirmed the issue and have a fix, but need to do a bit more testing first. We'll comment here when the change has been posted.

**Comment by jmagnotti** [comment]
Please run 
`rave::check_dependencies(nightly=TRUE)`
and you should be good to go. It looks like you're using an older version of RAVE, as the new demo subject is the aptly named DemoSubject rather than YAB. Feel free to submit a new issue if this doesn't solve your problem. Thanks!
