### ISSUE TITLE
Request function to export Voltage Diagnostic Plots

### ISSUE THREAD

**Issue by EANesbitt** [beauchamplab/rave#9]
In rave_preprocess, could you make a function that would export the graphs of the electrode diagnostics as a PNG file for quicker viewing?

**Comment by dipterix** [comment]
Function `export_diagnose_voltage` is implemented. Please update the package and try `?export_diagnose_voltage` or `help("export_diagnose_voltage")` to view the doc.

To export those images to a file, please do as follows: (let's say the subject is `project_1/sub_1` and it has 1-10 electrodes)

*(skip 1, and 2 if you have done so)*
1. First, please run import the subject. 
  a) Open `R`, import `rave` by `library(rave)`
  b) Open preprocess GUI by entering `rave_preprocess()`
  c) Create subject if not done, or find the subject if imported, specify sample rate, electrodes, as well as blocks, update subject 
2. go to "Notch filter", apply notch filter to all channels, then exit preprocessing module
3. Then, in R console, enter `export_diagnose_voltage("project_1/sub_1", electrodes = 1:10)`
